language: generic
sudo: required

services:
  - docker

script:
  - docker run -v $PWD:/recovery greenaddress/wallycore@sha256:654e5939446bfa8f33966031e768f6600e1d627b598e738e1d8f8427370786c7 /bin/bash -c "cd /recovery && virtualenv -p python3 venv && source venv/bin/activate && pip install --require-hashes -r tools/requirements_dev.txt && ./tools/dobuild.sh && rm -fr venv"
  - docker run -v $PWD:/recovery greenaddress/wallycore@sha256:059eeaa5c61df5403fd28d6ea556c317d5809f7274e27901d0f09288a316bb53 /bin/bash -c "cd /recovery && virtualenv -p python3 venv && source venv/bin/activate && pip install --require-hashes -r tools/requirements_dev.txt && ./tools/dobuild.sh && rm -fr venv"
  - docker run -v $PWD:/recovery greenaddress/wallycore@sha256:dd66cf18815756de37238c5fdfafc38c80076ce93d9ce644e517143894f24350 /bin/bash -c "cd /recovery && virtualenv -p python3 venv && source venv/bin/activate && pip install --require-hashes -r tools/requirements_dev.txt && ./tools/dobuild.sh && rm -fr venv"
